[workspace]
resolver = "2"
members = [
    "services/autoripper",
    "services/makemkv-cli"
]

[workspace.dependencies]
makemkv-core = { path = "libs/makemkv-core" }
handbrake-core = { path = "libs/handbrake-core" }
tmdb-client = { path = "libs/tmdb-client" }
utils = { path = "libs/utils" }
