max_width = 200
chain_width = 100

format_code_in_doc_comments = true
wrap_comments = true

imports_layout = "Horizontal"
struct_lit_single_line = true

fn_single_line = true
fn_params_layout = "Compressed"
fn_args_layout = "Compressed"
use_small_heuristics = "Max"
where_single_line = true
