[package]
name = "ripper"
version = "0.1.0"
edition = "2021"

[dependencies]
makemkv-core = { workspace = true }
tmdb-client = { workspace = true }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "time"] }
