name: Static CD Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/autoripper/frontend/**'
    branches:
      - 'main'

jobs:
  deploy:
    name: Build and publish the static build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node runtime
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20.x'
          cache-dependency-path: 'services/autoripper/frontend/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: services/autoripper/frontend

      - name: Build project
        run: pnpm build
        working-directory: services/autoripper/frontend
        env:
          VITE_BACKEND_BASE_URL: '/'
          VITE_BACKEND_WEBSOCKET_BASE_URL: '/'

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: services/autoripper/frontend/dist
